=== Beren1h/Bluepill/Bluepill.Search/User Configurations/configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="collections" type="collectionsType" minOccurs="1" maxOccurs="1" />
        <xs:element name="facets" type="facetsType" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
    <xs:unique name ="uniqueAspectId">
      <xs:selector xpath="facets/facet/aspect" />
      <xs:field xpath="@value" />
    </xs:unique>
    <xs:unique name ="uniqueFacetName">
      <xs:selector xpath="facets/facet" />
      <xs:field xpath="@name" />
    </xs:unique>
  </xs:element>

  <xs:complexType name="collectionsType">
    <xs:sequence>
      <xs:element name="collection" type="collectionType" minOccurs="0" maxOccurs="unbounded">
          <xs:unique name ="uniqueCollectionFacetName">
            <xs:selector xpath="facet" />
            <xs:field xpath="@name" />
          </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="collectionType">
    <xs:sequence>
      <xs:element name="facet" type="facetType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" />
  </xs:complexType>

  <xs:complexType name="facetsType">
    <xs:sequence>
      <xs:element name="facet" type="facetType" minOccurs="0" maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="facetType">
    <xs:sequence>
      <xs:element name="aspect" type="aspectType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" />
  </xs:complexType>

  <xs:complexType name="aspectType">
    <xs:attribute name="name" use="required" />
    <xs:attribute name="value" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="^.*[0-9]$"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

</xs:schema>

=== Beren1h/Bluepill/Bluepill.Search/User Configurations/uid.xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bluepill.org configuration.xsd">
  <collections>
    <collection name="Art">
      <facet name="Style" />
      <facet name="Mood" />
    </collection>
    <collection name="Home">
      <facet name="Style" />
      <facet name="Mood" />
      <facet name="1" />
      <facet name="2" />
      <facet name="3" />
      <facet name="4" />
    </collection>
  </collections>
  <facets>
    <facet name="1">
      <aspect name="100" value="100"/>
    </facet>
    <facet name="2">
      <aspect name="101" value="101"/>
    </facet>
      <facet name="3">
      <aspect name="102" value="102"/>
    </facet>
    <facet name="4">
      <aspect name="103" value="103"/>
    </facet>
    <facet name="Style">
      <aspect name="Photo" value="1" />
      <aspect name="Traditional" value="2" />
      <aspect name="Digital" value="3" />
      <aspect name="3D" value="4" />
      <aspect name="Sketch" value="9" />
    </facet>
    <facet name="Mood">
      <aspect name="Happy" value="5" />
      <aspect name="Sad" value="6" />
      <aspect name="Angry" value="7" />
      <aspect name="Grumpy" value="8" />
      <aspect name="Dopey" value="99" />
      <aspect name="Doc" value="10" />
      <aspect name="Sneezy" value="11" />
      <aspect name="Bashful" value="12" />
      <aspect name="Frodo" value="13" />
      <aspect name="Sam" value="14" />
      <aspect name="Pippin" value="15" />
      <aspect name="Merry" value="16" />
      <aspect name="Rosie" value="17" />
      <aspect name="Barney" value="18" />
      <aspect name="Ant Man" value="19" />
      <aspect name="This is a really, really, long name" value="20" />
      <aspect name="Atom" value="21" />
      <aspect name="fail1" value="221" />
      <aspect name="fail2" value="231" />
      <aspect name="fail3" value="211" />
    </facet>
  </facets>
</root>
